name: IncludePermission
version: 1.0
author: ChenhaoShen
main: com.raincubic.minecraft.Main
api-version: 1.15
soft-depend: [LuckPerms]

commands:
  includePermisson:
    description: 手动导入权限
    usage: /includePermission
    permission: permisson.include
    permission-message: §c你没有权限这么做
    aliases: [includeperm, inperm]

permissions:
  permission.include:
    description: 导入权限